/*jslint vars: true, nomen: true, indent: 4*/
/*global require, console, exports*/
(function () {
    "use strict";
    
    var spawn = require('child_process').spawn;
    
    function runCommand(config, callback) {
        var output = '', pylint,
            args = ['--msg-template="{line}:{column}:{category}:{msg}"',
                    '--report=n', '--persistent=n', '--rcfile=' + config.rcfilePath,
                   config.filePath];
        try {
            console.log('Will run "%s" with args = %s', config.pylintPath, JSON.stringify(args));
            pylint = spawn(config.pylintPath, args);
        } catch (err) {
            console.error('Pylint error = %s', err);
            return callback(err);
        }
        
        console.log('Setup pylint process handling...');
        
        pylint.stderr.on('data', function (data) {
            output += data.toString();
        });
        
        pylint.stdout.on('data', function (data) {
            output += data.toString();
        });
        
        pylint.on('exit', function (code, signal) {
            console.log('Lint process finished. Code = %s', code);
            var result = output.split(/\n\r?/);
            console.log('Lint results: ', result);
            return callback(null, result);
        });
    }
    
    function _init(domainManager) {
        if (domainManager.hasDomain('bracketsPylint')) {
            domainManager.registerDomain('bracketsPylint', {major: 0, minor: 1});
        }
        domainManager.registerCommand(
            'bracketsPylint',
            'run',
            runCommand,
            true,       // Asyncronous
            "Return linting result generated by a pylint process.",
            [{name: 'filePath', type: 'string', description: 'Full path of python file to be linted.'}],
            [{name: 'lines', type: 'object', description: 'Promise with linting results.'}]
        );
    }
    
    exports.init = _init;
}());
