/*jslint vars: true, nomen: true, indent: 4*/
/*global require, console, exports, jQuery */
(function () {
    "use strict";
    
    var fs = require('fs'),
        childp = require('child_process'),
        spawn = childp.spawn;

    function cmdLint(filePath) {
        var result = jQuery.Deferred(),
            output = '',
            args = [filePath, '--msg-template={line}:{msg}'],
            pylint = spawn('pylint', args);

        pylint.stdout.on('data', function (data) {
            output += data;
        });
        
        pylint.on('exit', function (code, signal) {
            result.resolve(output);
        });
        return result;
    }
    
    function _init(domainManager) {
        if (domainManager.hasDomain('pylint')) {
            domainManager.registerDomain('pylint', {major: 0, minor: 1});
        }
        
        domainManager.registerCommand(
            'pylint',
            'runPylint',
            cmdLint,
            true, // Asyncronous
            "Return linting result generated by a pylint process.",
            [{name: 'filePath', type: 'string', description: 'Full python source file to be linted.'}],
            [{name: 'lines', type: 'object', description: 'Promise with pylint execution'}]
        );
    }
    
    exports.init = _init;
}());
